<!DOCTYPE html>
<html lang="en" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:relative;min-height:100%;font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-size:62.5%;-webkit-tap-highlight-color:rgba(0,0,0,0);" >
  <head style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
    <meta charset="utf-8" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
    <meta name="viewport" content="width=device-width, initial-scale=1" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
    <title style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >Mail Template</title>
  </head>
  <body style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;line-height:1.42857143;color:#333;background-color:#fff;" >
    <div class="container" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;width:auto;max-width:680px;padding-top:0;padding-bottom:0;margin-right:auto;margin-left:auto;padding-left:15px;padding-right:15px;" >
      <div class="page-header" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-bottom:9px;margin-top:40px;margin-bottom:20px;margin-right:0;margin-left:0;border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:#eee;" >
        <h1 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin-right:0;margin-left:0;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:36px;" >Procbatch<small style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-weight:400;line-height:1;color:#999;font-size:65%;" > ${titulo}</small></h1>
      </div>
      <p class="lead" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin-top:0;margin-right:0;margin-left:0;margin-bottom:20px;font-size:16px;font-weight:200;line-height:1.4;" >Execução de script para correção de insconsistências no Filiaweb.</p>
	  <table class="table table-hover" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border-collapse:collapse;border-spacing:0;max-width:100%;background-color:transparent;width:100%;margin-bottom:20px;" >
      <thead style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
        <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
          <th style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;text-align:left;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;vertical-align:bottom;border-bottom-width:2px;border-bottom-style:solid;border-bottom-color:#ddd;" >#</th>
          <th style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;text-align:left;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;vertical-align:bottom;border-bottom-width:2px;border-bottom-style:solid;border-bottom-color:#ddd;" >First Name</th>
          <th style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;text-align:left;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;vertical-align:bottom;border-bottom-width:2px;border-bottom-style:solid;border-bottom-color:#ddd;" >Last Name</th>
          <th style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;text-align:left;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;vertical-align:bottom;border-bottom-width:2px;border-bottom-style:solid;border-bottom-color:#ddd;" >Username</th>
        </tr>
      </thead>
      <tbody style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
        <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >1</td>
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >Mark</td>
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >Otto</td>
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >@mdo</td>
        </tr>
        <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >2</td>
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >Jacob</td>
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >Thornton</td>
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >@fat</td>
        </tr>
        <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >3</td>
          <td colspan="2" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >Larry the Bird</td>
          <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-top:8px;padding-bottom:8px;padding-right:8px;padding-left:8px;line-height:1.42857143;vertical-align:top;border-top-width:1px;border-top-style:solid;border-top-color:#ddd;" >@twitter</td>
        </tr>
      </tbody>
    </table>
	<div align="center" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" >
	
	<button type="button" class="btn btn-primary btn-lg" onclick="location.href='http://procbatch-01.cad.apps.tse.jus.br:8080/procbatch/'" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-style:normal;font-variant:normal;margin-top:0;margin-right:0;margin-left:0;overflow:visible;text-transform:none;-webkit-appearance:button;font-family:inherit;display:inline-block;margin-bottom:0;font-weight:400;text-align:center;vertical-align:middle;cursor:pointer;background-image:none;border-width:1px;border-style:solid;white-space:nowrap;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;color:#fff;background-color:#428bca;border-color:#357ebd;padding-top:10px;padding-bottom:10px;padding-right:16px;padding-left:16px;font-size:18px;line-height:1.33;border-radius:6px;" >Acessar</button>
    <button type="button" class="btn btn-default btn-lg" onclick="location.href='mailto:procbatch@tse.jus.br'" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-style:normal;font-variant:normal;margin-top:0;margin-right:0;margin-left:0;overflow:visible;text-transform:none;-webkit-appearance:button;font-family:inherit;display:inline-block;margin-bottom:0;font-weight:400;text-align:center;vertical-align:middle;cursor:pointer;background-image:none;border-width:1px;border-style:solid;white-space:nowrap;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;color:#333;background-color:#fff;border-color:#ccc;padding-top:10px;padding-bottom:10px;padding-right:16px;padding-left:16px;font-size:18px;line-height:1.33;border-radius:6px;" >Reportar Problema</button>
		<br style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" />
		<br style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" />
    
	<ol class="breadcrumb" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin-top:0;padding-top:8px;padding-bottom:8px;padding-right:15px;padding-left:15px;margin-bottom:20px;list-style-type:none;list-style-position:outside;list-style-image:none;background-color:#f5f5f5;border-radius:4px;" >
  <li style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline-block;" ><a href="http://sticonhecimento.tse.jus.br/" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;background-image:none;background-repeat:repeat;background-position:0 0;background-attachment:scroll;color:#428bca;text-decoration:none;" >STI</a> /</li>
  <li style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline-block;" ><a href="http://sticonhecimento.tse.jus.br/csele" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;background-image:none;background-repeat:repeat;background-position:0 0;background-attachment:scroll;color:#428bca;text-decoration:none;" >CSELE</a> /</li>
  <li style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline-block;" ><a href="http://sticonhecimento.tse.jus.br/csele/secad" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;background-image:none;background-repeat:repeat;background-position:0 0;background-attachment:scroll;color:#428bca;text-decoration:none;" >SECAD</a></li>
</ol>
	<span class="label label-success" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline;padding-top:.2em;padding-bottom:.3em;padding-right:.6em;padding-left:.6em;font-size:75%;font-weight:700;line-height:1;color:#fff;text-align:center;white-space:nowrap;vertical-align:baseline;border-radius:.25em;background-color:#5cb85c;" >Mensagem gerada às 17:30:18 do dia 20/06/2014.</span>
	<br style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" />
	<span class="label label-warning" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline;padding-top:.2em;padding-bottom:.3em;padding-right:.6em;padding-left:.6em;font-size:75%;font-weight:700;line-height:1;color:#fff;text-align:center;white-space:nowrap;vertical-align:baseline;border-radius:.25em;background-color:#f0ad4e;" >appscad24.tse.jus.br / 192.168.10.13</span>
	<br style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;" />
	<span class="label label-danger" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline;padding-top:.2em;padding-bottom:.3em;padding-right:.6em;padding-left:.6em;font-size:75%;font-weight:700;line-height:1;color:#fff;text-align:center;white-space:nowrap;vertical-align:baseline;border-radius:.25em;background-color:#d9534f;" >Ambiente: Produção</span>
	</div>
	</div>
  </body>
</html>